New User Welcome Email
Code-Society-Lab/cursif-backend pull request #12
Opened 2023-09-03 06:34 UTC by chrisdedman

Issue -> https://github.com/Code-Society-Lab/cursif-backend/issues/11

2023-09-10 23:59 UTC, chrisdedman commented on lib/cursif_web/plugs/rate_limit.ex
I just remove the doc for the private function to remove the warning during compilation

2023-09-12 02:02 UTC, PenguinBoi12 requested changes
There's one big issue. When we validate, we're redirected to the backend, that's not really good, we should return the user to the client. In your issue you don't have to implement the client part but you have to think about it.

In a rest API we might want a `api/users/confirm/:token/` but in our case, since our API is a graphql API, it would most likely be cleaner to created a resolver that will verify the email. So, you most likely don't need any controller (that's my bad, I should've clicked when you talked about controllers)

To get the client's url we might be able to fetch the origin from the request. Otherwise, we could have an optional parameter passed containing the client's url or create client token (yes more tokens hahah).

So basically, instead of building the verify with the backend url it needs to be done with the client's url. The rest is good (except the route might be simplified by just calling it `verify` or something like that)


There's one thing that has been forgotten. The seeds, they create user but none of them are validated haha. It would probably be nice to validate them as we create them so we can use them 

In term of code, you did some good job. Well done! Ofc, some thing will change with the other token system but you don't have to worry about that.

2023-09-12 02:02 UTC, PenguinBoi12 commented on config/runtime.exs
> +# config :cursif, Cursif.Mailer,
Why everything is commented here?

2023-09-12 02:02 UTC, PenguinBoi12 commented on config/runtime.exs
> +  # config :swoosh, :api_client, Swoosh.ApiClient.Gmail
Originally it was ` Swoosh.ApiClient.Hackney`, can you please put it back.

2023-09-12 02:02 UTC, PenguinBoi12 commented on config/config.exs
You should be able to reset this file from origin by running `git checkout origin/main lib/config/config.exs`

2023-09-12 02:02 UTC, PenguinBoi12 commented on lib/cursif/accounts.ex
> +        if user.confirmed_at == nil do
You can use `is_nil(user.confirmed_at)`

2023-09-12 02:02 UTC, PenguinBoi12 commented on lib/cursif/accounts.ex
> +  def generate_validation_token(user) do
The point of `create_token(user, :phoenix_token)` is not to have to do this

2023-09-12 02:02 UTC, PenguinBoi12 commented on lib/cursif_web.ex
> +      # Use all HTML functionality (forms, tags, etc)
` import CursifWeb.ErrorHelpers` and ` import CursifWeb.Gettext` don't need to be imported and `should be imported in `view_helper`

2023-09-12 02:02 UTC, PenguinBoi12 commented on lib/cursif/accounts.ex
> +  def generate_confirmation_token(%User{} = user) do
I don't like that it's called `generate_confirmation_token` but also sends confirmation. Maybe `send_confirmation_email` would be better.

2023-09-12 02:02 UTC, PenguinBoi12 commented on lib/cursif_web/templates/email/welcome.html.eex
> +    body {
Have you looked/tried to put that in the `assets/css`?

2023-09-12 02:02 UTC, PenguinBoi12 commented on test/support/fixtures/accounts_fixtures.ex
> +    {:ok, user} = User.confirm_user_email(user)
`User.confirm_user_email` is slightly redundant. Maybe `User.confirm_email` is enough?

2023-09-12 02:09 UTC, chrisdedman commented on config/config.exs
This file has been restored from previous edition, with my new configuration as well.

2023-09-12 02:10 UTC, chrisdedman commented on lib/cursif_web/templates/email/welcome.html.eex
> +    body {
I am going to try that

2023-09-12 02:11 UTC, chrisdedman commented on lib/cursif_web.ex
> +      # Use all HTML functionality (forms, tags, etc)
Yes, you are right. Fixed

2023-09-12 02:11 UTC, chrisdedman commented on test/support/fixtures/accounts_fixtures.ex
> +    {:ok, user} = User.confirm_user_email(user)
Yes, you are right. Fixed!

2023-09-12 02:22 UTC, chrisdedman commented on config/runtime.exs
> +# config :cursif, Cursif.Mailer,
If I uncomment them, I cannot run the project locally.

2023-09-20 23:45 UTC, PenguinBoi12 requested changes
In general it's pretty good, the only issue is the configs. They are a bit of a mess. Otherwise, after that it should be fine. Well done!

2023-09-20 23:45 UTC, PenguinBoi12 commented on config/config.exs
> +  client_url: System.get_env("CLIENT_URL") || "http://localhost:3000"
It's better to do ` System.get_env("CLIENT_URL", "http://localhost:3000")`. Also, `config :cursif` is already defined at the top. Define it there instead. 

However, in my opinion it should be placed in `dev.exs`, that way we have a default only on dev (which is what we want; we want to force prod to define it)

2023-09-20 23:45 UTC, PenguinBoi12 commented on config/runtime.exs
> +  config :cursif,
Technically, it's already defined in `config.exs` but I've already talked about that in another comment. But this should all be in `prod.exs`. You shouldn't really modify `runtime.exs`

However, it's fine that it's defined isn't that bad although it should raise an error if undefined.

2023-09-20 23:45 UTC, PenguinBoi12 commented on config/prod.exs
> +  client_url: System.get_env("CLIENT_URL_PROD") || "http://localhost:3000"
`CLIENT_URL_PROD` the key should be the same as the other.   There's not use case of needing both at the same time.

2023-09-20 23:45 UTC, PenguinBoi12 commented on config/dev.exs
> +  client_url: System.get_env("CLIENT_URL_DEV") || "http://localhost:3000"
`CLIENT_URL_PROD` the key should be the same as the other.   There's not use case of needing both at the same time.

2023-09-20 23:45 UTC, PenguinBoi12 commented on lib/cursif_web/emails/user_email.ex
> +      |> from({"Cursif", "cursif@codesociety.xyz"})
When I think about it... This might also need to be a configuration.

2023-09-20 23:45 UTC, PenguinBoi12 commented on lib/cursif_web/plugs/rate_limit.ex
> -  @doc """
Why did you remove that comment?

2023-09-20 23:45 UTC, PenguinBoi12 commented on lib/cursif_web/views/layout_view.ex
Is it used or needed?

2023-09-20 23:47 UTC, chrisdedman commented on lib/cursif_web/plugs/rate_limit.ex
> -  @doc """
because it generate a warning at compiler time (because it is a private function)

2023-09-20 23:47 UTC, chrisdedman commented on lib/cursif_web/views/layout_view.ex
It is needed. Without it, it does not work

2023-09-21 03:06 UTC, PenguinBoi12 approved these changes

2023-09-21 03:06 UTC, PenguinBoi12 commented on config/config.exs
> +  email_address: "cursif@codesociety.xyz"
I meant this should be a env var too.

2023-09-21 03:12 UTC, merged