Add pages models and schemas
Code-Society-Lab/cursif-backend pull request #2
Opened 2023-03-29 01:20 UTC by MaanasArora

No tests added yet, but it would be appreciated if you could review it for any errors or changes.

I will add tests before this PR is merged.

Thank you!

2023-03-29 14:28 UTC, PenguinBoi12 requested changes
I am unsure if pages should have their own context or be added to the notebooks context (which doesn't exist yet on your branch and on the main branche). For some reason, my instinct tells me that page shouldn't have his own context. I'm saying that because I don't see `pages` be used outside of a notebook or at least out of a notebook context. 

To be faire, There's no notebook yet so don't worry about it. Beside, I am mostly thinking "out loud" and asking your opinion on this. What might simply happens is, I'll accept this and refactor it if I need to.

---

So far so good. The code seems pretty good. It would be nice to add the tests but otherwise it's awesome. Well done! Except for the test and, `has_many` and the absinthe schema thing, there's nothing else to change. 

Oh I would also change the name `contents` for `content`.

2023-03-29 14:28 UTC, PenguinBoi12 commented on lib/cursif/accounts/user.ex
> +    has_many :pages, Page, foreign_key: :author_id
A user doesn't have pages associated with him. The `belong_to` already does the job of associating the user and pages.

2023-03-29 14:28 UTC, PenguinBoi12 commented on lib/cursif_web/schema.ex
I've found a cleaner way, that also seems more idiomatic, to do the fields importation. You can check the notebook branch to see how [import](https://github.com/Code-Society-Lab/cursif/blob/notebook/lib/cursif_web/schema.ex) and their [definition](https://github.com/Code-Society-Lab/cursif/blob/notebook/lib/cursif_web/schema/notebook_types.ex).

2023-03-29 21:25 UTC, MaanasArora commented on lib/cursif/accounts/user.ex
> +    has_many :pages, Page, foreign_key: :author_id
Done!

2023-03-29 21:25 UTC, MaanasArora commented on lib/cursif_web/schema.ex
Done as well.

2023-03-30 16:24 UTC, PenguinBoi12 approved these changes
Has been merged with notebook

2023-03-30 16:25 UTC, closed without merging