Add favorites model and routing
Code-Society-Lab/cursif-backend pull request #30
Opened 2024-05-12 00:33 UTC by MaanasArora

Resolves #17.

Added favorite feature:
- Database model
- Migration
- Queries
- Resolvers
- Schemas

Sorry about the few styling changes that crept in (though to be fair, I have extraterrestial-style vision that can see trailing whitespace, and you should empathize with my agony)

2024-05-12 00:34 UTC, MaanasArora commented
PS I think I can make a few improvements to the schema. For example, perhaps updating notebooks shouldn't return a `favorite` field, that might be misleading. Still figuring out the best way to do that. Also, unit tests!

2024-05-13 01:11 UTC, chrisdedman requested changes
Overall, it is good. I added a couple of comments and potential changes which aren't too much of a big deal. Malassi will do the final review tho.

2024-05-13 01:11 UTC, chrisdedman commented on lib/cursif/notebooks.ex
> +    Repo.delete_all(from n in Favorite,
I wonder if in this case, using delete_all is necessary. I am thinking about using the function **delete()** from the Ecto library instead of **delete_all().** The result would be the same, but maybe it would be a better way to do it. Here is the [doc](https://hexdocs.pm/ecto/Ecto.Repo.html#c:delete/2) of what I am talking about. Let's see what Malassi thinks about this.

2024-05-13 01:11 UTC, chrisdedman commented on lib/cursif/notebooks.ex
> +             where: f.id == ^user.id or is_nil(f.id),
I think you will have a problem here. In your where clause, you are referencing f.id and comparing it to user.id which is the id of the user. So, comparing the id of the favorite notebook to the user id does not make sense and may not work (because of unique constraints). Something like this would probably be better ``left_join: f in assoc(n, :favorites), on: f.user_id == ^user.id,``. This way, it will make sure that the favorite table will be joined to the notebook table based on the constraint that both user_id's are matching.

2024-05-13 01:11 UTC, chrisdedman commented on lib/cursif/notebooks.ex
> +                 where: f.id == ^user_id or is_nil(f.id),
Same thing that I mentioned below (_check the comment line 64 on the get_notebook!()_)

2024-05-13 01:12 UTC, MaanasArora commented on lib/cursif/notebooks.ex
> +             where: f.id == ^user.id or is_nil(f.id),
That's actually not the case because each `favorite` is a `user`. Maybe we should rename the `favorites` `many_to_many` association.

2024-05-13 01:13 UTC, MaanasArora commented on lib/cursif/notebooks.ex
> +                 where: f.id == ^user_id or is_nil(f.id),
Same thing that I mentioned as well :D

2024-05-13 01:45 UTC, MaanasArora commented on lib/cursif/notebooks.ex
> +    Repo.delete_all(from n in Favorite,
I think `delete` _may_ be better, but I don't think it makes much of a difference.

2024-06-29 07:12 UTC, PenguinBoi12 approved these changes

2024-06-29 07:12 UTC, merged